kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080  # Use 8080 to avoid port conflicts
    protocol: TCP
  - containerPort: 443
    hostPort: 8443  # Use 8443 for HTTPS
    protocol: TCP