{{- if .Values.metrics.enable }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-runtime-operator.resourceName" (dict "suffix" "controller-manager-metrics-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.metrics.port }}
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
{{- end }}
