apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: hermes-runtime-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: hermes-runtime-operator-system
