{{- if and .Values.persistence.state.enabled (not .Values.persistence.state.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "runtime-node-core.fullname" . }}-state
  labels:
    {{- include "runtime-node-core.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.state.accessMode }}
  {{- if .Values.persistence.state.storageClassName }}
  storageClassName: {{ .Values.persistence.state.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.state.size }}
---
{{- end }}
{{- if and .Values.persistence.workspace.enabled (not .Values.persistence.workspace.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "runtime-node-core.fullname" . }}-workspace
  labels:
    {{- include "runtime-node-core.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.workspace.accessMode }}
  {{- if .Values.persistence.workspace.storageClassName }}
  storageClassName: {{ .Values.persistence.workspace.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspace.size }}
{{- end }}
