{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runtime-node-core.secretName" . }}
  labels:
    {{- include "runtime-node-core.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ .Values.secrets.keys.openai }}: {{ .Values.secrets.data.OPENAI_API_KEY | quote }}
  {{ .Values.secrets.keys.anthropic }}: {{ .Values.secrets.data.ANTHROPIC_API_KEY | quote }}
  {{ .Values.secrets.keys.openrouter }}: {{ .Values.secrets.data.OPENROUTER_API_KEY | quote }}
  {{ .Values.secrets.keys.opencode }}: {{ .Values.secrets.data.OPENCODE_GO_API_KEY | quote }}
{{- end }}
