apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-runtime-operator.resourceName" (dict "suffix" "controller-manager-api-secret" "context" $) }}
  namespace: {{ .Release.Namespace }}
stringData:
  CONTROLLER_SHARED_SECRET: generated-shared-secret
type: Opaque
