#!/usr/bin/env bash
# render-cluster-config.sh — embed the node cleanup install into a cluster config
#
# Reads a hetzner-k3s cluster config TEMPLATE containing the placeholder line:
#     # RENDER:cleanup-post-k3s-commands
# and replaces it with an `additional_post_k3s_commands:` block that installs the
# canonical cleanup script + systemd units on EVERY node (incl. autoscaled ones,
# which inherit this config). The script/units are embedded base64 — no boot-time
# GitHub fetch, no tokens on nodes.
#
# Output is deterministic. A header comment records the cleanup script sha256 so
# drift is visible in diffs and verifiable on-node by validate-cleanup.sh.
#
# Usage:
#   render-cluster-config.sh <template.yaml> [output.yaml]
#   (writes to stdout if no output path given)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE="${1:?Usage: render-cluster-config.sh <template.yaml> [output.yaml]}"
OUT="${2:-/dev/stdout}"
PLACEHOLDER="# RENDER:cleanup-post-k3s-commands"

CLEANUP_SH="$SCRIPT_DIR/hermescloud-cleanup.sh"
CLEANUP_SVC="$SCRIPT_DIR/hermescloud-cleanup.service"
CLEANUP_TIMER="$SCRIPT_DIR/hermescloud-cleanup.timer"

for f in "$TEMPLATE" "$CLEANUP_SH" "$CLEANUP_SVC" "$CLEANUP_TIMER"; do
  [ -f "$f" ] || { echo "error: not found: $f" >&2; exit 1; }
done
grep -qF "$PLACEHOLDER" "$TEMPLATE" || {
  echo "error: template '$TEMPLATE' has no '$PLACEHOLDER' placeholder" >&2; exit 1; }

b64()  { base64 -w0 "$1"; }
HASH=$(sha256sum "$CLEANUP_SH" | awk '{print $1}')
B64_SH=$(b64 "$CLEANUP_SH")
B64_SVC=$(b64 "$CLEANUP_SVC")
B64_TIMER=$(b64 "$CLEANUP_TIMER")

# Build the replacement block. Each list item is a single shell command so
# hetzner-k3s passes them cleanly to the node's post-k3s phase.
BLOCK=$(cat <<EOF
# ── BEGIN generated cleanup install (render-cluster-config.sh) ────────────────
# cleanup script sha256: $HASH
# Regenerate with: render-cluster-config.sh <template> <output>  — do not hand-edit.
additional_post_k3s_commands:
  - "echo $B64_SH | base64 -d > /usr/local/bin/hermescloud-cleanup"
  - "chmod +x /usr/local/bin/hermescloud-cleanup"
  - "echo $B64_SVC | base64 -d > /etc/systemd/system/hermescloud-cleanup.service"
  - "echo $B64_TIMER | base64 -d > /etc/systemd/system/hermescloud-cleanup.timer"
  - "echo $HASH > /etc/hermescloud-cleanup.version"
  - "systemctl daemon-reload"
  - "systemctl enable --now hermescloud-cleanup.timer"
  - "/usr/local/bin/hermescloud-cleanup --dry-run || true"
# ── END generated cleanup install ─────────────────────────────────────────────
EOF
)

# Replace the placeholder line with the block (awk to avoid sed escaping issues).
TMP=$(mktemp)
{
  echo "# GENERATED by render-cluster-config.sh from $(basename "$TEMPLATE")"
  echo "# cleanup sha256: $HASH — DO NOT hand-edit the generated cleanup block"
  echo ""
  awk -v ph="$PLACEHOLDER" -v block="$BLOCK" '
    index($0, ph) { print block; next }
    { print }
  ' "$TEMPLATE"
} > "$TMP"

if [ "$OUT" = "/dev/stdout" ]; then cat "$TMP"; else mv "$TMP" "$OUT"; echo "rendered → $OUT (cleanup sha256 $HASH)" >&2; fi
[ "$OUT" = "/dev/stdout" ] && rm -f "$TMP"
exit 0
