{{- if not .Values.operator.enabled }}
{{- if .Values.resourceQuota.enabled }}
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ include "hermes-agent.fullname" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hard:
    pods: "1"
    persistentvolumeclaims: "2"
    requests.cpu: {{ .Values.resources.requests.cpu | quote }}
    requests.memory: {{ .Values.resources.requests.memory | quote }}
    limits.cpu: {{ .Values.resources.limits.cpu | quote }}
    limits.memory: {{ .Values.resources.limits.memory | quote }}
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "hermes-agent.fullname" . }}
  labels:
    {{- include "hermes-agent.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.resources.limits.cpu | quote }}
        memory: {{ .Values.resources.limits.memory | quote }}
      defaultRequest:
        cpu: {{ .Values.resources.requests.cpu | quote }}
        memory: {{ .Values.resources.requests.memory | quote }}
      max:
        cpu: {{ .Values.resources.limits.cpu | quote }}
        memory: {{ .Values.resources.limits.memory | quote }}
{{- end }}
{{- end }}
